###

GET {{host-url}}/all

###

POST {{host-url}}//newAdd
Content-Type: application/json

{
  "id": -1,
  "first": "Julian",
  "last": "Rice",
  "password": "123321",
  "email": "julian.rice@bizreach.co.jp",
  "phone": "",
  "name": "",
  "hometown": "",
  "division": "",
  "friendList": []
}

###