###

GET {{host-url}}/all

###

GET http://localhost:8080/users/14

###

POST {{host-url}}//newAdd
Content-Type: application/json

{
  "id": -1,
  "first": "Julian",
  "last": "Rice",
  "password": "123321",
  "email": "julian.rice@bizreach.co.jp",
  "phone": "",
  "name": "",
  "hometown": "",
  "division": "",
  "friendList": []
}

###

GET {{host-url}}//user

###
GET {{host-url}}//checkUser?email=albert@onetwothree.com&pw=321321
#Content-Type: application/json
#
#{
#  "username": "albert@onetwothree.com",
#  "password": "321321"
#}